// Code generated by go-bindata. DO NOT EDIT.
// sources:
// sql/20180606143811_add_users.down.sql
// sql/20180606143811_add_users.up.sql
// sql/20180606150206_add_devices.down.sql
// sql/20180606150206_add_devices.up.sql
package migrations

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __20180606143811_add_usersDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\xf0\xf4\x73\x71\x8d\x50\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x2d\x4e\x2d\x2a\x8e\x2f\xcd\x4c\x89\xcf\x4c\x29\x56\x70\x76\x0c\x76\x76\x74\x71\xb5\xe6\xe2\x02\x2b\x0e\x71\x74\xf2\x71\x45\x57\x8c\xae\xc8\x35\x22\xc4\xd5\x2f\xd8\xd3\xdf\x0f\x49\x61\x41\x7a\x72\x51\x65\x41\x49\xbe\x35\x20\x00\x00\xff\xff\xac\xc3\x03\x6d\x74\x00\x00\x00")

func _20180606143811_add_usersDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__20180606143811_add_usersDownSql,
		"20180606143811_add_users.down.sql",
	)
}

func _20180606143811_add_usersDownSql() (*asset, error) {
	bytes, err := _20180606143811_add_usersDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "20180606143811_add_users.down.sql", size: 116, mode: os.FileMode(420), modTime: time.Unix(1528296183, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __20180606143811_add_usersUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x8f\x41\x4e\xc3\x30\x10\x45\xf7\x3e\xc5\x5f\x36\x12\x37\xe8\xca\xa5\x53\x31\xc2\x71\x4a\x3c\x51\x13\x36\x51\x88\x2d\x64\x81\x44\x94\xda\x88\xde\x1e\x25\x02\x21\xa0\xcb\x99\xff\xde\xe2\xdd\xd6\xa4\x85\x40\xad\x90\x75\x5c\x59\xf0\x01\xb6\x12\x50\xcb\x4e\x1c\xa6\xe7\x71\xbe\x4c\xe9\x6d\xab\xd4\x17\x29\x7a\x67\xe8\x0f\x95\xcf\x61\x3e\x63\xa3\x80\xe8\xe1\xa8\x66\x6d\x70\xac\xb9\xd4\x75\x87\x7b\xea\x6e\x14\x90\xa3\x87\x50\x2b\xab\x66\x1b\x63\x96\xe7\x34\xc7\xf7\x21\x85\xfe\x25\x5c\xb0\xeb\x84\xf4\xef\x35\x3f\xbd\xc6\x71\x1d\xff\x99\xe3\x1c\x86\x14\x7c\x3f\x24\x08\x97\xe4\x44\x97\x47\x9c\x58\xee\xd6\x13\x8f\x95\x25\xec\xe9\xa0\x1b\xb3\x78\xa7\x4d\xa1\x8a\x9f\x84\xc6\xf2\x43\x43\x60\xbb\xa7\xf6\x5a\x49\x9f\xa3\xef\xa3\xff\x50\x40\x65\xbf\xe3\x72\xf4\xc5\xf6\x33\x00\x00\xff\xff\x22\x68\x0f\x28\x2e\x01\x00\x00")

func _20180606143811_add_usersUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__20180606143811_add_usersUpSql,
		"20180606143811_add_users.up.sql",
	)
}

func _20180606143811_add_usersUpSql() (*asset, error) {
	bytes, err := _20180606143811_add_usersUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "20180606143811_add_users.up.sql", size: 302, mode: os.FileMode(420), modTime: time.Unix(1528296951, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __20180606150206_add_devicesDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\x48\x49\x2d\xcb\x4c\x4e\x2d\x56\x70\x76\x0c\x76\x76\x74\x71\xb5\xe6\xe2\x82\x48\x46\x06\xb8\x2a\x78\xba\x29\xb8\x46\x78\x06\x87\x04\x2b\xa4\x64\x16\x17\xe4\x17\x67\x96\x64\xe6\xe7\xc1\x55\x02\x02\x00\x00\xff\xff\x48\xe8\xe5\x19\x45\x00\x00\x00")

func _20180606150206_add_devicesDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__20180606150206_add_devicesDownSql,
		"20180606150206_add_devices.down.sql",
	)
}

func _20180606150206_add_devicesDownSql() (*asset, error) {
	bytes, err := _20180606150206_add_devicesDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "20180606150206_add_devices.down.sql", size: 69, mode: os.FileMode(420), modTime: time.Unix(1528300830, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __20180606150206_add_devicesUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x90\xcf\x8e\xaa\x30\x14\xc6\xf7\x3c\xc5\xb7\x13\x12\xdf\xc0\x55\xd5\xe3\xbd\xcd\x85\xc2\x2d\x25\xca\x6c\x08\x63\x9b\x49\xa3\xa1\x06\x8a\x99\x79\xfb\x09\x8d\x4e\x30\x4e\x26\xb3\x3b\x3d\xdf\x9f\xb6\xbf\x8d\x24\xa6\x08\xaa\x2e\x08\xda\x0e\x17\x37\x58\x6f\x5d\x07\x56\x82\x44\x95\x21\x5e\xd8\x4e\x3b\xd7\x2f\x96\x58\xb8\xd1\x87\x31\x59\x45\xd1\x3d\xc7\xd6\x29\x81\xef\x20\x72\x05\x3a\xf0\x52\x95\xd0\xe6\x6a\x8f\x66\x40\x1c\x01\x56\xa3\x24\xc9\x59\x8a\x42\xf2\x8c\xc9\x1a\xff\xa8\x5e\x46\x80\x77\x27\xd3\x41\xd1\x41\x85\xa8\xa8\xd2\x74\x5a\x8f\x83\xe9\x1b\xab\xc1\x85\xa2\x3f\x24\xbf\x34\x48\xda\x91\x24\xb1\xa1\x32\x78\x86\xd8\xea\x64\x0a\x5c\x7a\x7b\x6d\xbd\x69\x4e\xe6\x03\xeb\x5a\x11\x7b\xa8\xbb\x8c\xaf\x67\x7b\x0c\xe2\xd3\x55\x67\xd7\xbd\x59\x3f\x6a\x83\x6d\x5e\x4d\xbf\x28\x24\x6d\x78\xc9\x73\xf1\x68\x6b\xfd\x2f\x5c\x73\x74\xf3\x79\xee\x39\xf6\xa6\xf5\x46\x37\xad\x87\xe2\x19\x95\x8a\x65\x05\xf6\x5c\xfd\x0d\x47\xbc\xe4\x82\xb0\xa5\x1d\xab\xd2\xe9\xa1\xfb\x38\x89\x66\xa0\x2b\xc1\xff\x57\x04\x2e\xb6\x74\xf8\x9e\x77\x13\x90\x36\x56\xbf\x47\x40\x2e\xee\xeb\x38\xac\x67\x4d\x3f\x55\xdc\xf0\x3f\x97\xdc\x84\x64\xf5\x19\x00\x00\xff\xff\x89\xc1\x29\x5d\x30\x02\x00\x00")

func _20180606150206_add_devicesUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__20180606150206_add_devicesUpSql,
		"20180606150206_add_devices.up.sql",
	)
}

func _20180606150206_add_devicesUpSql() (*asset, error) {
	bytes, err := _20180606150206_add_devicesUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "20180606150206_add_devices.up.sql", size: 560, mode: os.FileMode(420), modTime: time.Unix(1528300492, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"20180606143811_add_users.down.sql": _20180606143811_add_usersDownSql,
	"20180606143811_add_users.up.sql": _20180606143811_add_usersUpSql,
	"20180606150206_add_devices.down.sql": _20180606150206_add_devicesDownSql,
	"20180606150206_add_devices.up.sql": _20180606150206_add_devicesUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"20180606143811_add_users.down.sql": &bintree{_20180606143811_add_usersDownSql, map[string]*bintree{}},
	"20180606143811_add_users.up.sql": &bintree{_20180606143811_add_usersUpSql, map[string]*bintree{}},
	"20180606150206_add_devices.down.sql": &bintree{_20180606150206_add_devicesDownSql, map[string]*bintree{}},
	"20180606150206_add_devices.up.sql": &bintree{_20180606150206_add_devicesUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

